### ISSUE TITLE
Warning during test run: "Invalid DOM property `autocomplete`"

### ISSUE THREAD

**Issue by alex-polunochev** [react-tags/react-tags#777]
Version 6.7.0
Warning shows up during test run for component that uses `react-tag-input`:

```
 console.error
    Warning: Invalid DOM property `autocomplete`. Did you mean `autoComplete`?
        at input
        at div
        at div
        at div
        at ReactTags (/Users/.../node_modules/react-tag-input/dist-modules/components/ReactTags.js:68:5)
        at DndProvider (/Users/.../node_modules/react-dnd/dist/cjs/core/DndProvider.js:39:23)
```

**Comment by alex-polunochev** [comment]
After more thorough checking I found that the problem wasn't on the library side, but was coming from my code.
```
      <ReactTags
        inputProps={{ autocomplete: 'disabled' }}
       ...
```

Closing the ticket. Thanks!

**Comment by ad1992** [comment]
Thanks for confirming @alex-polunochev
